collections: 
  posts:
    output: true
    permalink: /blog/:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      main_class: post

title: Binyamin Green | Developer, Designer, Musician, Nerd
desc: Binyamin Green is a student in practice and a web developer at heart. He is currently workinbg on DevMe (https://GetDevMe.com).

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1