collections: 
  posts:
    output: true
    permalink: /blog/:title
  drafts:
    output: true
    permalink: /drafts/:title
  
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      main_class: post
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: post
      main_class: post

title: "Binyamin Green | Student & Web Developer"
desc: "Binyamin Green is a student and web developer specializing in front-end websites. He is based out of Baltimore, Maryland in the heart of the Jewish, orthodox community."

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1