# netlify.toml

[build]
  publish = "dist/"
  command = "npm run build"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/gifts"
  to = "https://www.gifthero.com/list/c94b429f-1dfa-4ab2-95d8-ad8094446ed7"

[[redirects]]
  from = "/listening"
  to = "https://visualify.io/share/MB4iQ9yTQtgjtYpGC"

[[redirects]]
  from = "/profile.jpeg"
  to = "/assets/img/profile/profile.jpeg"

[[headers]]
  for = "/**/*"
  [headers.values]
    cache-control = '''
      max-age=31536000,
      no-cache'''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
