# netlify.toml

[build]
  publish = "dist/"
  command = "npm run compile"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/listening"
  to = "https://visualify.io/share/MB4iQ9yTQtgjtYpGC"

[[redirects]]
  from = "/profile.jpeg"
  to = "/assets/img/profile/profile.jpeg"


# Temporary redirects (6 months ?)

[[redirects]]
  from = "/blog/"
  to = "/c/blog"

[[redirects]]
  from = "/blog/*"
  to = "/p/:splat"

[[redirects]]
  from = "/micro/"
  to = "/c/micro"

[[redirects]]
  from = "/micro/*"
  to = "/p/:splat"

[[headers]]
  for = "/**/*"
  [headers.values]
    cache-control = '''
      max-age=31536000,
      no-cache'''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
