name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  a11y:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: npm install -g @lhci/cli
      - run: lhci autorun
  # broken_links:
  #   if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, '[skip ci]')"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 12.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - run: npm ci
  #     - run: node scripts/fetchNotes.js
  #     - run: npm install @binyamin/lincoln wait-on -g
  #     - name: Validate links
  #       run: |
  #         npm start &
  #         wait-on "http://localhost:8080" && lincoln http://localhost:8080
  #     - run: kill $(jobs -p) || true
